### PR TITLE
Meerim

### PR DESCRIPTION
**Pull request by AlimAlan**
Group 17 Please review my code!

### CODE REVIEW

**Comment by daudbaz** [comment]
Good Job 👏

**Review by daudbaz — APPROVED** [review]

**Review by sel-erdem — APPROVED** [review]
Well done Meerim 👍

**Comment by KateCherkasova** [comment]
we need one more approval here

**Review by KateCherkasova — APPROVED** [review]

**Comment by GeryaM** [comment]
Awesome

**Pull request merged**
