### PR TITLE
Round 2 of pull request, incoming

### PR DESCRIPTION
**Pull request by daudbaz**
Here we go for round 2 of pull requests :)

### CODE REVIEW

**Review by KateCherkasova — APPROVED** [review]

**Comment by crazyfrog2** [comment]
Great job, bestie!

**Review by crazyfrog2 — APPROVED** [review]
Love your code!

**Review by nancyshenouda — APPROVED** [review]
looks cool

**Review by sel-erdem — APPROVED** [review]
yes yes yes

**Review by AlimAlan — APPROVED** [review]
looks good, approved

**Pull request merged**
