### PR TITLE
US1069

### PR DESCRIPTION
**Pull request by sel-erdem**
Day 2Same Project

### CODE REVIEW

**Review by KateCherkasova — APPROVED** [review]
Great job, Sel!

**Review by AlimAlan — APPROVED** [review]
approving

**Review by GeryaM — COMMENTED** [review]
I LOVE, ❤️ 💕 💗 💖 💘

**Comment by KateCherkasova** [comment]
I can't approve this one for some reason, just comment.
Hello hello 🥄

**Comment by GeryaM** [comment]
JUST 3 approval can be, I put a block as he said

**Comment by GeryaM** [comment]
Kate you already approved

**Comment by sel-erdem** [comment]
Maria, you didnt approve, you left a comment

**Review by KateCherkasova — APPROVED** [review]
Looking good, thank you for the review request!

**Comment by GeryaM** [comment]
I know, I am letting other to do it

**Comment by daudbaz** [comment]
You can do better

**Comment by NevzatM** [comment]
Hey

**Review by daudbaz — APPROVED** [review]

**Comment by GeryaM** [comment]
Ok, Sel merge it

**Comment by sel-erdem** [comment]
stop yelling at me :(

**Pull request merged**
