### PR TITLE
Kate practice july7

### PR DESCRIPTION
**Pull request by KateCherkasova**
practice makes perfect

### CODE REVIEW

**Review by daudbaz — APPROVED** [review]

**Review by sel-erdem — APPROVED** [review]
next time insert dog photo or i cannot approve

**Review by AlimAlan — APPROVED** [review]
approving

**Comment by GeryaM** [comment]
Kate sorry for late response. How have you been?

**Comment by Bahruzexcel** [comment]
hey

**Comment by Bahruzexcel** [comment]
hey

**Pull request merged**
