### PR TITLE
Nancy 07 01 2021

### PR DESCRIPTION
**Pull request by nancyshenouda**
can u please review my code

### CODE REVIEW

**Review by GeryaM — CHANGES_REQUESTED** [review]
Hello Nancy please add line 4!

**Review by sel-erdem — COMMENTED** [review]
Commit 1 looks good!

**Review by KateCherkasova — CHANGES_REQUESTED** [review]
Hello Nancy, can you please add  commit 5. Thank you! : - )

**Review by AlimAlan — CHANGES_REQUESTED** [review]
Nancy, please change  line 7 to System.out.print()

**Review by KateCherkasova — COMMENTED** [review]
Great job, thank you Nancy!

**Review by GeryaM — APPROVED** [review]
Good Job!

**Review by AlimAlan — APPROVED** [review]
Good Job Nancy

**Review by sel-erdem — APPROVED** [review]
Commit 4 approved :)

**Review by Bahruzexcel — APPROVED** [review]
good code

**Review by GeryaM — APPROVED** [review]
Approved!

**Review by AlimAlan — APPROVED** [review]
approving

**Review by Bahruzexcel — APPROVED** [review]
great code

**Review by KateCherkasova — APPROVED** [review]

**Pull request merged**
