### PR TITLE
bahruz added

### PR DESCRIPTION
**Pull request by GeryaM**
Hello Bahruz, I received your code! Can you please reply

### CODE REVIEW

**Comment by Bahruzexcel** [comment]
Hey Masha i replied

**Comment by GeryaM** [comment]
Please add one line to the code

**Comment by Bahruzexcel** [comment]
i add just one line in HalloGroup17

**Comment by AlimAlan** [comment]
great work Bahruz

**Review by GeryaM — COMMENTED** [review]
This is cool code

**Pull request merged**
