### PR TITLE
Us 002

### PR DESCRIPTION
**Pull request by Bahruzexcel**
please check my code

### CODE REVIEW

**Comment by Bahruzexcel** [comment]
guys could you check my code plz

**Review by KateCherkasova — APPROVED** [review]
great dedication, lovin it )

**Review by AlimAlan — CHANGES_REQUESTED** [review]
Bahruz, extra practice for you! write quickly   fibonachi number!
joking
just add  one more line

**Review by sel-erdem — APPROVED** [review]
Well done bahruz, thank you for putting your favorite instructor in there too for bonus points ))

**Review by KateCherkasova — APPROVED** [review]

**Comment by Bahruzexcel** [comment]
Sel i added you as Assignnees and i update my request. i do know what wil happen))

**Review by crazyfrog2 — APPROVED** [review]
Great code!

**Review by GeryaM — APPROVED** [review]
Unbelivible

**Review by sel-erdem — APPROVED** [review]

**Review by nancyshenouda — APPROVED** [review]
approved

**Review by Bahruzexcel — COMMENTED** [review]
great code

**Review by Bahruzexcel — COMMENTED** [review]
afsf

**Pull request merged**
