### PR TITLE
Us500

### PR DESCRIPTION
**Pull request by Darus811**
Requesting a pull request

### CODE REVIEW

**Review by sel-erdem — APPROVED** [review]
Well Done Darus, i like us500 and its contents

**Comment by GeryaM** [comment]
Darus, awesome job!

**Comment by GeryaM** [comment]
approved

**Comment by daudbaz** [comment]
good job Darus

**Review by AlimAlan — APPROVED** [review]
approved

**Review by daudbaz — APPROVED** [review]
Good Job on the awsome code

**Comment by crazyfrog2** [comment]
Great job, Darus!

**Review by GeryaM — APPROVED** [review]

**Review by crazyfrog2 — APPROVED** [review]
Approved!

**Pull request merged**
