### PR TITLE
Kate practice july7

### PR DESCRIPTION
**Pull request by KateCherkasova**
my old push just popped out..hmm. can you pls approve? no conflicts here though

### CODE REVIEW

**Review by AlimAlan — APPROVED** [review]
great, as usual!

**Comment by daudbaz** [comment]
of course, you always have great code. APPROVED

**Review by daudbaz — APPROVED** [review]
good job

**Review by daudbaz — APPROVED** [review]
good job

**Review by sel-erdem — APPROVED** [review]
well done

**Pull request merged**
