### PR TITLE
Kate branch

### PR DESCRIPTION
**Pull request by KateCherkasova**
Work is done pls let me know if you need any changes to be made. ty

### CODE REVIEW

**Review by sel-erdem — APPROVED** [review]
all 5 commits look great, @Bahruzexcel please go to general chat

**Review by nancyshenouda — APPROVED** [review]

**Review by GeryaM — APPROVED** [review]
Well Done

**Review by AlimAlan — APPROVED** [review]
Good job Kate!

**Review by Bahruzexcel — COMMENTED** [review]
very good Kate

**Review by Bahruzexcel — APPROVED** [review]
great job Kate

**Pull request merged**
