### PR TITLE
Tanya completed

### PR DESCRIPTION
**Pull request by crazyfrog2**
Finished my class

### CODE REVIEW

**Review by sel-erdem — APPROVED** [review]
Hey Tanya,
This code about another awsome student is very amazing and over my head, too difficult for me to solve. I will approve and try to be awsome too :)

**Review by nancyshenouda — APPROVED** [review]
cool

**Comment by daudbaz** [comment]
No I am back :)

**Review by daudbaz — APPROVED** [review]
Good Job on the code. Landed 5:30am yesterday :)

**Pull request merged**
